#!/bin/bash

#Copyright (c) 2012 Amndeep Singh Mann <Amndeep.dev@gmail.com>
#Please see License.txt for more information.  

#Dependent on the scripts convertfromnetpbm and removenetpbm

#Arguments: (optional) 1 = Directory where the images are stores (make sure to end it with a "/")

DIRECTORY="$HOME/RandomArtAssignmentPictures/"
if [ $# -ne 0 ]
then
	DIRECTORY=$1
fi
./convertfromnetpbm "$DIRECTORY"
./removenetpbm "$DIRECTORY"
