#!/bin/bash

#Copyright (c) 2012 Amndeep Singh Mann <Amndeep.dev@gmail.com>
#Please see License.txt for more information.  

while [ 1 -eq 1 ]
do
	echo Starting picture `date`
	time java -jar RandomArtAssignment\ -\ Bare.jar "$@"
	echo Ending picture `date`
done
