#!/bin/bash

#Copyright (c) 2012 Amndeep Singh Mann <Amndeep.dev@gmail.com>
#Please see License.txt for more information.  

CURRENTDIRECTORY=`pwd`
cd bin
echo Starting picture `date`
java randomartassignment.picture.DriverParallel "$@"
echo Ending picture `date`
cd "$CURRENTDIRECTORY"
