#!/bin/bash

#Copyright (c) 2012 Amndeep Singh Mann <Amndeep.dev@gmail.com>
#Please see License.txt for more information.  

#Arguments: 1 = Time type, as defined later; 2 = End time

#Time type for the date command, use the same types (M, H, etc.) just without the %
TIMETYPE=$1
TIMETILL=$2
shift
shift
CURRENTDIRECTORY=`pwd`
cd bin
CURRENTTIME=`date +%$TIMETYPE`
while [ "$CURRENTTIME" -lt "$TIMETILL" ]
do
	echo Starting picture `date`
	time java randomartassignment.picture.DriverParallel "$@"
	echo Ending picture `date`
	CURRENTTIME=`date +%$TIMETYPE`
done
cd "$CURRENTDIRECTORY"
